services:
  mongo:
    container_name: vivo-back-mongo-1
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - db-mongo-vivo:/data/db
    ports:
      - 27017:27017
volumes:
  db-mongo-vivo:
